
/// <reference path="../coalesce.dependencies.d.ts" />

// Generated by IntelliTect.Coalesce

module ViewModels {
    export class Person extends PersonPartial {
        
        constructor(newItem?: object, parent?: Coalesce.BaseViewModel | ListViewModels.PersonList) {
            super(newItem, parent);
            
        }
    }
}
