trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

variables:
  webDir: $(Build.Repository.LocalPath)/Coalesce.Starter.Vue.Web

steps:
  - checkout: self
    lfs: true

  - task: UseDotNet@2
    inputs:
      packageType: "sdk"
      version: "8.x"
      includePreviewVersions: true
      performMultiLevelLookup: true

  - task: UseNode@1
    inputs:
      version: "24.x"

  - script: npm install -g pnpm@11
    displayName: Install pnpm

  - script: pnpm install --frozen-lockfile
    displayName: pnpm install
    workingDirectory: $(webDir)

  - task: DotNetCoreCLI@2
    inputs:
      command: "restore"
    displayName: Restore Nuget packages

  - task: PowerShell@2
    inputs:
      targetType: "inline"
      script: |
        dotnet coalesce --what-if --verify
      failOnStderr: true
      workingDirectory: "$(webDir)"
    displayName: Check Coalesce has run

  - script: pnpm lint
    displayName: pnpm lint
    workingDirectory: $(webDir)

  - script: pnpm build
    displayName: pnpm build
    workingDirectory: $(webDir)

  - task: DotNetCoreCLI@2
    displayName: dotnet build
    inputs:
      command: "build"
      arguments: "--configuration Release --no-restore --no-incremental -p:CodeAnalysisTreatWarningsAsErrors=true -p:TreatWarningsAsErrors=true"

  - task: DotNetCoreCLI@2
    displayName: dotnet test
    inputs:
      command: "test"
      arguments: "--no-build --configuration Release"

  - task: DotNetCoreCLI@2
    displayName: dotnet publish
    inputs:
      command: "publish"
      publishWebProjects: true
      arguments: --no-build --configuration Release -o $(Build.ArtifactStagingDirectory)

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: "$(Build.ArtifactStagingDirectory)"
      ArtifactName: "drop"
      publishLocation: "Container"
