import type { Component } from "vue";
import type { DefaultTheme, Header } from "vitepress";

/** Module id of the manifest and page loaders generated by `vitepressDocs`. */
export const VIRTUAL_MODULE_ID = "virtual:coalesce-vue-docs";
/** Module id of the search index generated by `vitepressDocs`. */
export const SEARCH_MODULE_ID = "virtual:coalesce-vue-docs-search";

/** One searchable section: a page's text between two of its headings. */
export interface DocSearchSection {
  id: string;
  /** App URL of the page. */
  path: string;
  /** Heading id to scroll to; empty for the text above the first subheading. */
  anchor: string;
  pageTitle: string;
  heading: string;
  text: string;
}

export interface DocsManifest {
  /** URL the docs are mounted at, with a trailing slash. */
  base: string;
  sidebar: DefaultTheme.Sidebar;
}

export interface DocMeta {
  title: string;
  frontmatter: Record<string, unknown>;
  headers: Header[];
  /** Path of the source file relative to the docs directory. */
  relativePath: string;
  /** App URL that serves this page. */
  docPath: string;
  /** URL directory this page's relative links resolve against. */
  docDir: string;
}

export interface DocModule {
  default: Component;
  meta: DocMeta;
}

export interface DocPage {
  /** Module id of the markdown source, e.g. `/docs/guide/getting-started.md`. */
  file: string;
  /** App URL that serves the page, e.g. `/docs/guide/getting-started`. */
  path: string;
  load: () => Promise<DocModule>;
}

function trimSlashes(base: string) {
  return base.replace(/\/+$/, "");
}

/**
 * Maps a source path relative to the docs directory onto the app URL serving
 * it. An `index.md` takes the URL of its directory.
 */
export function docPath(base: string, relativePath: string): string {
  // No trailing slash, on any page: vue-router resolves the docs route's
  // `:path(.*)*` with an empty param back to a slash-free path, so a canonical
  // URL that kept one could never be navigated to.
  const withoutExtension = relativePath.replace(/\.md$/, "");
  const withoutIndex = withoutExtension.replace(/(?:^|\/)index$/, "");
  const prefix = trimSlashes(base);
  return withoutIndex ? `${prefix}/${withoutIndex}` : prefix;
}

/**
 * The URL directory a page's relative links resolve against: its source
 * directory, which `docPath` loses because a directory index and a sibling
 * page get the same URL shape.
 */
export function docDir(base: string, relativePath: string): string {
  const prefix = trimSlashes(base);
  const slash = relativePath.lastIndexOf("/");
  return slash < 0
    ? `${prefix}/`
    : `${prefix}/${relativePath.slice(0, slash)}/`;
}

/**
 * The single URL a doc page is served at. A link may arrive with a trailing
 * slash, or spelled `.../index` the way VitePress's link plugin writes a
 * directory index.
 */
export function canonicalDocPath(path: string, base: string): string {
  return (
    path.replace(/\/+$/, "").replace(/\/index$/, "") || trimSlashes(base) || "/"
  );
}

function withBase(link: string, base: string): string {
  if (/^(?:[a-z]+:)?\/\//i.test(link) || !link.startsWith("/")) return link;
  const joined = trimSlashes(base) + link;
  return joined.length > 1 ? joined.replace(/\/+$/, "") : joined;
}

function withBaseSidebarItems(
  items: DefaultTheme.SidebarItem[],
  base: string,
): DefaultTheme.SidebarItem[] {
  return items.map((item) => ({
    ...item,
    link: item.link ? withBase(item.link, base) : undefined,
    items: item.items ? withBaseSidebarItems(item.items, base) : undefined,
  }));
}

/**
 * Prefixes sidebar links with `base`. They are authored without it, the way
 * VitePress's own theme expects them, but vue-router needs the full path.
 */
export function withBaseSidebar(
  sidebar: DefaultTheme.Sidebar,
  base: string,
): DefaultTheme.Sidebar {
  if (Array.isArray(sidebar)) return withBaseSidebarItems(sidebar, base);

  return Object.fromEntries(
    Object.entries(sidebar).map(([prefix, value]) => [
      withBase(prefix, base) || base,
      Array.isArray(value)
        ? withBaseSidebarItems(value, base)
        : { ...value, items: withBaseSidebarItems(value.items, base) },
    ]),
  ) as DefaultTheme.Sidebar;
}
