using IntelliTect.Coalesce.CodeGeneration.Generation;
using System;
using System.Collections.Generic;
using System.Text;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using System.IO;
using System.Linq;

namespace IntelliTect.Coalesce.CodeGeneration.Knockout.Generators
{
    public class TsReferencesFile : StringBuilderFileGenerator<List<IGenerator>>
    {
        public TsReferencesFile(GeneratorServices services, ILoggerFactory loggerFactory) : base(services) { }

        public override Task<string> BuildOutputAsync()
        {
            var sb = new StringBuilder();
            sb.AppendLine();
            sb.AppendLine();
            sb.AppendLine("// This file is automatically generated.");
            sb.AppendLine("// It is not in the generated folder for ease-of-use (no relative paths).");
            sb.AppendLine("// This file must remain in place relative to the generated scripts (<WebProject>/Scripts/Generated).");
            sb.AppendLine();
            sb.AppendLine();
            sb.AppendLine($"/// <reference path=\"coalesce.dependencies.d.ts\" />");

            foreach (var referencePath in Model.Select(m => m.OutputPath).OrderBy(p => p))
            {
                // https://stackoverflow.com/a/1766773/2465631
                Uri referencedFilePath = new Uri(referencePath);
                Uri referenceFile = new Uri(this.OutputPath);
                Uri diff = referenceFile.MakeRelativeUri(referencedFilePath);
                string relPath = diff.OriginalString;

                sb.AppendLine($"/// <reference path=\"{relPath}\" />");
            }

            return Task.FromResult(sb.ToString());
        }
    }
}
