


// This file is automatically generated.
// It is not in the generated folder for ease-of-use (no relative paths).



/// <reference path="\Coalesce\intellitect.ko.base.ts" />
/// <reference path="\Coalesce\intellitect.ko.bindings.ts" />
/// <reference path="\Coalesce\intellitect.ko.utilities.ts" />
/// <reference path="\Coalesce\intellitect.utilities.ts" />
/// <reference path="Generated\Ko.Case.ts" />
/// <reference path="Generated\Ko.CaseDto.ts" />
/// <reference path="Generated\Ko.CaseDtoList.ts" />
/// <reference path="Generated\Ko.CaseList.ts" />
/// <reference path="Generated\Ko.CaseProduct.ts" />
/// <reference path="Generated\Ko.CaseProductList.ts" />
/// <reference path="Generated\Ko.CaseSummary.ts" />
/// <reference path="Generated\Ko.Company.ts" />
/// <reference path="Generated\Ko.CompanyList.ts" />
/// <reference path="Generated\Ko.DevTeam.ts" />
/// <reference path="Generated\Ko.DevTeamList.ts" />
/// <reference path="Generated\Ko.Person.ts" />
/// <reference path="Generated\Ko.PersonList.ts" />
/// <reference path="Generated\Ko.PersonStats.ts" />
/// <reference path="Generated\Ko.Product.ts" />
/// <reference path="Generated\Ko.ProductList.ts" />
