

// This file is automatically generated.
// It is not in the generated folder for ease-of-use (no relative paths).
// This file must remain in place relative to the generated scripts (<WebProject>/Scripts/Generated).


/// <reference path="coalesce.dependencies.d.ts" />
/// <reference path="Generated/Ko.Case.ts" />
/// <reference path="Generated/Ko.CaseDto.ts" />
/// <reference path="Generated/Ko.CaseDtoList.ts" />
/// <reference path="Generated/Ko.CaseList.ts" />
/// <reference path="Generated/Ko.CaseProduct.ts" />
/// <reference path="Generated/Ko.CaseProductList.ts" />
/// <reference path="Generated/Ko.CaseSummary.ts" />
/// <reference path="Generated/Ko.Company.ts" />
/// <reference path="Generated/Ko.CompanyList.ts" />
/// <reference path="Generated/Ko.DevTeam.ts" />
/// <reference path="Generated/Ko.Person.Partial.ts" />
/// <reference path="Generated/Ko.PersonList.ts" />
/// <reference path="Generated/Ko.PersonStats.ts" />
/// <reference path="Generated/Ko.Product.ts" />
/// <reference path="Generated/Ko.ProductList.ts" />
/// <reference path="Partials/Ko.Person.partial.ts" />
