

// This file is automatically generated.
// It is not in the generated folder for ease-of-use (no relative paths).
// This file must remain in place relative to the generated scripts (<WebProject>/Scripts/Generated).


/// <reference path="coalesce.dependencies.d.ts" />
/// <reference path="Generated/Ko.Case.g.ts" />
/// <reference path="Generated/Ko.CaseDto.g.ts" />
/// <reference path="Generated/Ko.CaseDtoList.g.ts" />
/// <reference path="Generated/Ko.CaseList.g.ts" />
/// <reference path="Generated/Ko.CaseProduct.g.ts" />
/// <reference path="Generated/Ko.CaseProductList.g.ts" />
/// <reference path="Generated/Ko.CaseSummary.g.ts" />
/// <reference path="Generated/Ko.Company.g.ts" />
/// <reference path="Generated/Ko.CompanyList.g.ts" />
/// <reference path="Generated/Ko.DevTeam.g.ts" />
/// <reference path="Generated/Ko.Location.g.ts" />
/// <reference path="Generated/Ko.Person.Partial.g.ts" />
/// <reference path="Generated/Ko.PersonCriteria.g.ts" />
/// <reference path="Generated/Ko.PersonList.g.ts" />
/// <reference path="Generated/Ko.PersonStats.g.ts" />
/// <reference path="Generated/Ko.Product.g.ts" />
/// <reference path="Generated/Ko.ProductList.g.ts" />
/// <reference path="Generated/Ko.WeatherData.g.ts" />
/// <reference path="Generated/Ko.WeatherServiceClient.g.ts" />
/// <reference path="Partials/Ko.Person.partial.ts" />
