// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/fb2b3b1e068c9ff7d8f9b0851c08d37d96c95c38/moment/moment.d.ts
declare var moment: moment.MomentStatic;
