// <auto-generated />
using Coalesce.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Coalesce.Domain.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20180226172924_Testing")]
    partial class Testing
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Coalesce.Domain.Case", b =>
                {
                    b.Property<int>("CaseKey")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AssignedToId");

                    b.Property<byte[]>("Attachment");

                    b.Property<string>("Description");

                    b.Property<int?>("DevTeamAssignedId");

                    b.Property<TimeSpan>("Duration");

                    b.Property<DateTimeOffset>("OpenedAt");

                    b.Property<int?>("ReportedById");

                    b.Property<string>("Severity");

                    b.Property<int>("Status");

                    b.Property<string>("Title");

                    b.HasKey("CaseKey");

                    b.HasIndex("AssignedToId");

                    b.HasIndex("ReportedById");

                    b.ToTable("Case");
                });

            modelBuilder.Entity("Coalesce.Domain.CaseProduct", b =>
                {
                    b.Property<int>("CaseProductId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CaseId");

                    b.Property<int>("ProductId");

                    b.HasKey("CaseProductId");

                    b.HasIndex("CaseId");

                    b.HasIndex("ProductId");

                    b.ToTable("CaseProduct");
                });

            modelBuilder.Entity("Coalesce.Domain.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address1");

                    b.Property<string>("Address2");

                    b.Property<string>("City");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name");

                    b.Property<string>("State");

                    b.Property<string>("ZipCode");

                    b.HasKey("CompanyId");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("Coalesce.Domain.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("BirthDate");

                    b.Property<int>("CompanyId");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName")
                        .HasMaxLength(75);

                    b.Property<int>("Gender");

                    b.Property<DateTime?>("LastBath");

                    b.Property<string>("LastName")
                        .HasMaxLength(100);

                    b.Property<DateTimeOffset?>("NextUpgrade");

                    b.Property<byte[]>("ProfilePic");

                    b.Property<int>("Title");

                    b.HasKey("PersonId");

                    b.HasIndex("CompanyId");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("Coalesce.Domain.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ProductId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Coalesce.Domain.Case", b =>
                {
                    b.HasOne("Coalesce.Domain.Person", "AssignedTo")
                        .WithMany("CasesAssigned")
                        .HasForeignKey("AssignedToId");

                    b.HasOne("Coalesce.Domain.Person", "ReportedBy")
                        .WithMany("CasesReported")
                        .HasForeignKey("ReportedById");
                });

            modelBuilder.Entity("Coalesce.Domain.CaseProduct", b =>
                {
                    b.HasOne("Coalesce.Domain.Case", "Case")
                        .WithMany("CaseProducts")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Coalesce.Domain.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Coalesce.Domain.Person", b =>
                {
                    b.HasOne("Coalesce.Domain.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Coalesce.Domain.Product", b =>
                {
                    b.OwnsOne("Coalesce.Domain.ProductDetails", "Details", b1 =>
                        {
                            b1.Property<int>("ProductId");

                            b1.ToTable("Product");

                            b1.HasOne("Coalesce.Domain.Product")
                                .WithOne("Details")
                                .HasForeignKey("Coalesce.Domain.ProductDetails", "ProductId")
                                .OnDelete(DeleteBehavior.Cascade);

                            b1.OwnsOne("Coalesce.Domain.StreetAddress", "CompanyHqAddress", b2 =>
                                {
                                    b2.Property<int>("ProductDetailsProductId");

                                    b2.Property<string>("Address");

                                    b2.Property<string>("City");

                                    b2.Property<string>("PostalCode");

                                    b2.Property<string>("State");

                                    b2.ToTable("Product");

                                    b2.HasOne("Coalesce.Domain.ProductDetails")
                                        .WithOne("CompanyHqAddress")
                                        .HasForeignKey("Coalesce.Domain.StreetAddress", "ProductDetailsProductId")
                                        .OnDelete(DeleteBehavior.Cascade);
                                });

                            b1.OwnsOne("Coalesce.Domain.StreetAddress", "ManufacturingAddress", b2 =>
                                {
                                    b2.Property<int>("ProductDetailsProductId");

                                    b2.Property<string>("Address");

                                    b2.Property<string>("City");

                                    b2.Property<string>("PostalCode");

                                    b2.Property<string>("State");

                                    b2.ToTable("Product");

                                    b2.HasOne("Coalesce.Domain.ProductDetails")
                                        .WithOne("ManufacturingAddress")
                                        .HasForeignKey("Coalesce.Domain.StreetAddress", "ProductDetailsProductId")
                                        .OnDelete(DeleteBehavior.Cascade);
                                });
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
