name: docs

on:
  push:
    branches: [dev]
    paths: ["docs/**"]
  pull_request:
    branches: [dev]
    paths: ["docs/**"]

  # trigger deployment manually
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: docs

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          # fetch all commits to get last updated time or other git log info
          fetch-depth: 0

      - run: npm ci
        working-directory: ${{ github.workspace }}

      - run: npm run build

      # please check out the docs of the workflow for more details
      # @see https://github.com/crazy-max/ghaction-github-pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        if: github.event_name != 'pull_request'
        with:
          # deploy to gh-pages branch
          target_branch: gh-pages
          build_dir: docs/.vitepress/dist/Coalesce
          jekyll: false
        env:
          # @see https://docs.github.com/en/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
